version: '3'

services:
  cv-nvcnet:
    build: .
    container_name: cv-nvcnet
    image: cv-nvcnet-image
    shm_size: '24gb'
    tty: true
    volumes:
      - /mnt/hdd/audio:/data
      - $PWD:/nvc_net
    command: '/bin/bash'
    ports:
      - 18051-18060:18051-18060
    runtime: nvidia
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #      - driver: nvidia
    #        capabilities: [gpu]
