version: '3'

services:
  cv-nvcnet:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.gpu
    container_name: cv-nvcnet
    image: cv-nvcnet-image
    shm_size: '24gb'
    tty: true
    volumes:
      - $PWD:/workspace
    command: '/bin/bash'
    ports:
      - 18051-18060:18051-18060
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [gpu]
