version: '3'

services:
  cv-nvcnet:
    build: 
      context: .
      dockerfile: ./.docker/Dockerfile.cpu
    container_name: cv-nvcnet-dev
    image: cv-nvcnet-image
    shm_size: '24gb'
    tty: true
    volumes: 
      - $PWD:/workspace
    command: 'jupyter-lab --allow-root --port 18082 --ip 0.0.0.0 --no-browser'
    ports:
      - 18051-18060:18051-18060